/**
 * Care Plan Generator helpers.
 *
 * Subtotal is integer USD cents from the treatments catalog
 * (`quantity * treatments.priceCents`). Payment quotes are derived from that
 * subtotal. See docs/WEEK11-CARE-PLANS.md.
 *
 * Patient first/last name and notes are ePHI (encrypted at rest).
 */

import { centsToDollars } from "./kpis";

function formatPriceCents(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(centsToDollars(cents));
}

export const CARE_PLAN_STATUSES = ["draft", "final"] as const;
export type CarePlanStatus = (typeof CARE_PLAN_STATUSES)[number];

export const MAX_CARE_PLAN_NAME = 80;
export const MAX_CARE_PLAN_NOTES = 4_000;
export const MAX_TEMPLATE_NAME = 120;
export const MAX_TREATMENT_QUANTITY = 10_000;
export const MAX_DISCOUNT_PERCENT = 100;
export const MAX_PLAN_MONTHS = 120;
export const MAX_SELECTIONS = 200;

export const DEFAULT_COMPLIANCE_NOTICE = [
  "Chiropractic care plan regulations, including required disclosures, fee schedules, and patient agreement formats, vary by state.",
  "The care plans generated by this tool are provided as a financial planning aid only. It is solely your responsibility as the licensed practitioner to ensure that your care plans comply with all applicable laws and regulations in your state.",
  'By clicking "I Acknowledge" you confirm that you understand this notice and accept full responsibility for ensuring compliance with your state’s chiropractic care plan requirements.',
].join("\n\n");

export const DEFAULT_CARE_PLAN_TERMS = `{practiceName} declares that the care plan offered in our office is not insurance in any capacity. Therefore it is understood that we make no representations about treating new conditions outside of the scope of this agreement for care in our office.

The Patient is responsible for notifying {practiceName} within 3 days if an accident or injury occurs that changes the patient's health status or could impact this care plan.

Should the Patient's status change due to a personal injury, worker's compensation, or other such claim, {practiceName} will suspend this agreement while providing care for these new injuries or conditions. The care provided during the suspension period for these new conditions will be administered per our usual and customary fees. Once the patient is released from care concerning the new injury or condition, care provided under this agreement will resume.

The patient recognizes that this agreement is not a promise or guarantee of results. The agreement exists to create the financial options relative to the services and products included in this care plan. This agreement between the patient and {practiceName} is non-transferable.`;

export const CARE_PLAN_PDF_COMPLIANCE_FOOTER =
  "This care plan is a financial planning aid only. Compliance with applicable state chiropractic care-plan rules is the licensed practitioner’s responsibility. Generated by Chiro-KPI.";

export const CARE_PLAN_GENERATOR = {
  available: true as const,
  path: "/care-plan-calculator",
  reason:
    "Care Plan Generator is available after the practitioner acknowledges the compliance notice.",
};

export type CarePlanTreatmentSelection = {
  treatmentId: string;
  quantity: number;
  /** Snapshot at save time (not PHI). Used if the catalog row is later removed. */
  name?: string;
  unitPriceCents?: number;
};

export type PayInFullSettings = {
  enabled: boolean;
  discountPercent: number;
};

export type MonthlyPlanSettings = {
  enabled: boolean;
  discountPercent: number;
  months: number;
};

export type DownPaymentPlanSettings = {
  enabled: boolean;
  discountPercent: number;
  months: number;
  downPaymentPercent: number;
};

/**
 * Stored on `care_plans.payment_settings` and inside template
 * `default_selections.paymentSettings`.
 *
 * - `payInFull`: one-time amount after percent discount (Platinum).
 * - `monthlyPlan`: equal monthly payments after percent discount (Silver).
 * - `downPaymentPlan`: percent down + remaining / months (Gold).
 * - `planStartDate`: optional `YYYY-MM-DD` (UTC calendar).
 *
 * Percents are 0–100. Months are 1–120. Money in quotes is integer cents.
 */
export type CarePlanPaymentSettings = {
  payInFull: PayInFullSettings;
  monthlyPlan: MonthlyPlanSettings;
  downPaymentPlan: DownPaymentPlanSettings;
  planStartDate: string | null;
};

export type CarePlanTemplateSelections = {
  treatmentSelections: CarePlanTreatmentSelection[];
  paymentSettings: CarePlanPaymentSettings;
};

export type TreatmentPriceLookup = {
  id: string;
  name: string;
  category: string;
  priceCents: number;
  active: boolean;
};

export type CarePlanLineItem = {
  treatmentId: string;
  name: string;
  category: string | null;
  quantity: number;
  unitPriceCents: number;
  unitPrice: number;
  unitPriceDisplay: string;
  lineTotalCents: number;
  lineTotal: number;
  lineTotalDisplay: string;
  missingFromCatalog: boolean;
};

export type PayInFullQuote = {
  discountPercent: number;
  discountCents: number;
  totalCents: number;
  total: number;
  totalDisplay: string;
};

export type MonthlyPlanQuote = {
  discountPercent: number;
  discountCents: number;
  totalCents: number;
  total: number;
  totalDisplay: string;
  months: number;
  monthlyPaymentCents: number;
  monthlyPayment: number;
  monthlyPaymentDisplay: string;
};

export type DownPaymentPlanQuote = {
  discountPercent: number;
  discountCents: number;
  totalCents: number;
  total: number;
  totalDisplay: string;
  downPaymentPercent: number;
  downPaymentCents: number;
  downPayment: number;
  downPaymentDisplay: string;
  months: number;
  monthlyPaymentCents: number;
  monthlyPayment: number;
  monthlyPaymentDisplay: string;
};

export type CarePlanPaymentQuotes = {
  payInFull: PayInFullQuote | null;
  monthlyPlan: MonthlyPlanQuote | null;
  downPaymentPlan: DownPaymentPlanQuote | null;
};

export const DEFAULT_PAYMENT_SETTINGS: CarePlanPaymentSettings = {
  payInFull: { enabled: true, discountPercent: 10 },
  monthlyPlan: { enabled: true, discountPercent: 5, months: 6 },
  downPaymentPlan: {
    enabled: true,
    discountPercent: 7,
    months: 4,
    downPaymentPercent: 30,
  },
  planStartDate: null,
};

export function isCarePlanStatus(value: string): value is CarePlanStatus {
  return (CARE_PLAN_STATUSES as readonly string[]).includes(value);
}

export function percentOfCents(cents: number, percent: number): number {
  return Math.round((cents * percent) / 100);
}

function moneyFields(cents: number): { dollars: number; display: string } {
  return { dollars: centsToDollars(cents), display: formatPriceCents(cents) };
}

function clampInt(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, Math.round(value)));
}

function readNumber(raw: unknown): number | undefined {
  if (typeof raw === "number" && Number.isFinite(raw)) return raw;
  if (typeof raw === "string" && raw.trim() !== "") {
    const n = Number(raw);
    if (Number.isFinite(n)) return n;
  }
  return undefined;
}

function readBool(raw: unknown, fallback: boolean): boolean {
  if (typeof raw === "boolean") return raw;
  return fallback;
}

export function normalizeTreatmentSelections(
  raw: unknown,
):
  | { ok: true; selections: CarePlanTreatmentSelection[] }
  | { ok: false; error: string } {
  if (raw == null) {
    return { ok: true, selections: [] };
  }

  const collected: CarePlanTreatmentSelection[] = [];

  if (Array.isArray(raw)) {
    for (const item of raw) {
      if (!item || typeof item !== "object") {
        return { ok: false, error: "invalid_selections" };
      }
      const row = item as Record<string, unknown>;
      const treatmentId =
        typeof row.treatmentId === "string"
          ? row.treatmentId.trim()
          : typeof row.id === "string"
            ? row.id.trim()
            : "";
      if (!treatmentId) return { ok: false, error: "invalid_selections" };
      const quantity = readNumber(row.quantity) ?? 0;
      if (!Number.isInteger(quantity) || quantity < 0) {
        return { ok: false, error: "invalid_quantity" };
      }
      if (quantity === 0) continue;
      if (quantity > MAX_TREATMENT_QUANTITY) {
        return { ok: false, error: "quantity_too_large" };
      }
      const name = typeof row.name === "string" ? row.name.trim() : undefined;
      const unitPriceCents = readNumber(row.unitPriceCents);
      collected.push({
        treatmentId,
        quantity,
        ...(name ? { name } : {}),
        ...(unitPriceCents != null &&
        Number.isInteger(unitPriceCents) &&
        unitPriceCents >= 0
          ? { unitPriceCents }
          : {}),
      });
    }
  } else if (typeof raw === "object") {
    for (const [treatmentId, qtyRaw] of Object.entries(
      raw as Record<string, unknown>,
    )) {
      const id = treatmentId.trim();
      if (!id) continue;
      const quantity = readNumber(qtyRaw) ?? 0;
      if (!Number.isInteger(quantity) || quantity < 0) {
        return { ok: false, error: "invalid_quantity" };
      }
      if (quantity === 0) continue;
      if (quantity > MAX_TREATMENT_QUANTITY) {
        return { ok: false, error: "quantity_too_large" };
      }
      collected.push({ treatmentId: id, quantity });
    }
  } else {
    return { ok: false, error: "invalid_selections" };
  }

  const merged = new Map<string, CarePlanTreatmentSelection>();
  for (const row of collected) {
    const existing = merged.get(row.treatmentId);
    if (!existing) {
      merged.set(row.treatmentId, { ...row });
      continue;
    }
    const quantity = Math.min(
      MAX_TREATMENT_QUANTITY,
      existing.quantity + row.quantity,
    );
    merged.set(row.treatmentId, {
      ...existing,
      quantity,
      name: row.name ?? existing.name,
      unitPriceCents: row.unitPriceCents ?? existing.unitPriceCents,
    });
  }

  const selections = [...merged.values()];
  if (selections.length > MAX_SELECTIONS) {
    return { ok: false, error: "too_many_selections" };
  }
  return { ok: true, selections };
}

export function normalizePaymentSettings(
  raw: unknown,
):
  | { ok: true; settings: CarePlanPaymentSettings }
  | { ok: false; error: string } {
  const base: CarePlanPaymentSettings = {
    payInFull: { ...DEFAULT_PAYMENT_SETTINGS.payInFull },
    monthlyPlan: { ...DEFAULT_PAYMENT_SETTINGS.monthlyPlan },
    downPaymentPlan: { ...DEFAULT_PAYMENT_SETTINGS.downPaymentPlan },
    planStartDate: null,
  };
  if (raw == null) return { ok: true, settings: base };
  if (typeof raw !== "object") return { ok: false, error: "invalid_payment_settings" };
  const obj = raw as Record<string, unknown>;

  const pif = obj.payInFull;
  if (pif && typeof pif === "object") {
    const row = pif as Record<string, unknown>;
    const discount =
      readNumber(row.discountPercent) ?? readNumber(row.discount) ?? 10;
    if (discount < 0 || discount > MAX_DISCOUNT_PERCENT) {
      return { ok: false, error: "invalid_discount" };
    }
    base.payInFull = {
      enabled: readBool(row.enabled, true),
      discountPercent: clampInt(discount, 0, MAX_DISCOUNT_PERCENT),
    };
  }

  const monthly = obj.monthlyPlan;
  if (monthly && typeof monthly === "object") {
    const row = monthly as Record<string, unknown>;
    const discount =
      readNumber(row.discountPercent) ?? readNumber(row.discount) ?? 5;
    const months = readNumber(row.months) ?? 6;
    if (discount < 0 || discount > MAX_DISCOUNT_PERCENT) {
      return { ok: false, error: "invalid_discount" };
    }
    if (months < 1 || months > MAX_PLAN_MONTHS || !Number.isInteger(months)) {
      return { ok: false, error: "invalid_months" };
    }
    base.monthlyPlan = {
      enabled: readBool(row.enabled, true),
      discountPercent: clampInt(discount, 0, MAX_DISCOUNT_PERCENT),
      months,
    };
  }

  const down = obj.downPaymentPlan;
  if (down && typeof down === "object") {
    const row = down as Record<string, unknown>;
    const discount =
      readNumber(row.discountPercent) ?? readNumber(row.discount) ?? 7;
    const months = readNumber(row.months) ?? 4;
    const downPct =
      readNumber(row.downPaymentPercent) ??
      readNumber(row.downPaymentPercentage) ??
      30;
    if (discount < 0 || discount > MAX_DISCOUNT_PERCENT) {
      return { ok: false, error: "invalid_discount" };
    }
    if (months < 1 || months > MAX_PLAN_MONTHS || !Number.isInteger(months)) {
      return { ok: false, error: "invalid_months" };
    }
    if (downPct < 0 || downPct > MAX_DISCOUNT_PERCENT) {
      return { ok: false, error: "invalid_down_payment" };
    }
    base.downPaymentPlan = {
      enabled: readBool(row.enabled, true),
      discountPercent: clampInt(discount, 0, MAX_DISCOUNT_PERCENT),
      months,
      downPaymentPercent: clampInt(downPct, 0, MAX_DISCOUNT_PERCENT),
    };
  }

  if (obj.planStartDate === null || obj.planStartDate === "") {
    base.planStartDate = null;
  } else if (typeof obj.planStartDate === "string") {
    const value = obj.planStartDate.trim();
    if (value && !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
      return { ok: false, error: "invalid_plan_start_date" };
    }
    base.planStartDate = value || null;
  }

  return { ok: true, settings: base };
}

export function snapshotSelections(
  selections: CarePlanTreatmentSelection[],
  catalog: TreatmentPriceLookup[],
):
  | { ok: true; selections: CarePlanTreatmentSelection[]; subtotalCents: number }
  | { ok: false; error: string; treatmentId?: string } {
  const byId = new Map(catalog.map((row) => [row.id, row]));
  const out: CarePlanTreatmentSelection[] = [];
  let subtotalCents = 0;
  for (const sel of selections) {
    const treatment = byId.get(sel.treatmentId);
    if (!treatment) {
      return { ok: false, error: "unknown_treatment", treatmentId: sel.treatmentId };
    }
    subtotalCents += treatment.priceCents * sel.quantity;
    out.push({
      treatmentId: sel.treatmentId,
      quantity: sel.quantity,
      name: treatment.name,
      unitPriceCents: treatment.priceCents,
    });
  }
  return { ok: true, selections: out, subtotalCents };
}

export function computeSubtotalCents(
  selections: CarePlanTreatmentSelection[],
  catalog: TreatmentPriceLookup[],
):
  | { ok: true; subtotalCents: number }
  | { ok: false; error: string; treatmentId?: string } {
  const snapped = snapshotSelections(selections, catalog);
  if (!snapped.ok) return snapped;
  return { ok: true, subtotalCents: snapped.subtotalCents };
}

export function buildLineItems(
  selections: CarePlanTreatmentSelection[],
  catalog: TreatmentPriceLookup[],
): { items: CarePlanLineItem[]; subtotalCents: number } {
  const byId = new Map(catalog.map((row) => [row.id, row]));
  const items: CarePlanLineItem[] = [];
  let subtotalCents = 0;
  for (const sel of selections) {
    const treatment = byId.get(sel.treatmentId);
    const unitPriceCents =
      treatment?.priceCents ??
      (typeof sel.unitPriceCents === "number" ? sel.unitPriceCents : 0);
    const name = treatment?.name ?? sel.name ?? "Removed service";
    const lineTotalCents = unitPriceCents * sel.quantity;
    subtotalCents += lineTotalCents;
    const unit = moneyFields(unitPriceCents);
    const line = moneyFields(lineTotalCents);
    items.push({
      treatmentId: sel.treatmentId,
      name,
      category: treatment?.category ?? null,
      quantity: sel.quantity,
      unitPriceCents,
      unitPrice: unit.dollars,
      unitPriceDisplay: unit.display,
      lineTotalCents,
      lineTotal: line.dollars,
      lineTotalDisplay: line.display,
      missingFromCatalog: !treatment,
    });
  }
  return { items, subtotalCents };
}

export function computePaymentQuotes(
  subtotalCents: number,
  settings: CarePlanPaymentSettings,
): CarePlanPaymentQuotes {
  const quotes: CarePlanPaymentQuotes = {
    payInFull: null,
    monthlyPlan: null,
    downPaymentPlan: null,
  };
  if (subtotalCents <= 0) return quotes;

  if (settings.payInFull.enabled) {
    const discountCents = percentOfCents(
      subtotalCents,
      settings.payInFull.discountPercent,
    );
    const totalCents = subtotalCents - discountCents;
    const total = moneyFields(totalCents);
    quotes.payInFull = {
      discountPercent: settings.payInFull.discountPercent,
      discountCents,
      totalCents,
      total: total.dollars,
      totalDisplay: total.display,
    };
  }

  if (settings.monthlyPlan.enabled) {
    const months = Math.max(1, settings.monthlyPlan.months);
    const discountCents = percentOfCents(
      subtotalCents,
      settings.monthlyPlan.discountPercent,
    );
    const totalCents = subtotalCents - discountCents;
    const monthlyPaymentCents = Math.round(totalCents / months);
    const total = moneyFields(totalCents);
    const monthly = moneyFields(monthlyPaymentCents);
    quotes.monthlyPlan = {
      discountPercent: settings.monthlyPlan.discountPercent,
      discountCents,
      totalCents,
      total: total.dollars,
      totalDisplay: total.display,
      months,
      monthlyPaymentCents,
      monthlyPayment: monthly.dollars,
      monthlyPaymentDisplay: monthly.display,
    };
  }

  if (settings.downPaymentPlan.enabled) {
    const months = Math.max(1, settings.downPaymentPlan.months);
    const discountCents = percentOfCents(
      subtotalCents,
      settings.downPaymentPlan.discountPercent,
    );
    const totalCents = subtotalCents - discountCents;
    const downPaymentCents = percentOfCents(
      totalCents,
      settings.downPaymentPlan.downPaymentPercent,
    );
    const remaining = totalCents - downPaymentCents;
    const monthlyPaymentCents = Math.round(remaining / months);
    const total = moneyFields(totalCents);
    const down = moneyFields(downPaymentCents);
    const monthly = moneyFields(monthlyPaymentCents);
    quotes.downPaymentPlan = {
      discountPercent: settings.downPaymentPlan.discountPercent,
      discountCents,
      totalCents,
      total: total.dollars,
      totalDisplay: total.display,
      downPaymentPercent: settings.downPaymentPlan.downPaymentPercent,
      downPaymentCents,
      downPayment: down.dollars,
      downPaymentDisplay: down.display,
      months,
      monthlyPaymentCents,
      monthlyPayment: monthly.dollars,
      monthlyPaymentDisplay: monthly.display,
    };
  }

  return quotes;
}

export function applyPracticeName(template: string, practiceName: string): string {
  return template.replaceAll("{practiceName}", practiceName);
}

export function addMonthsYmd(ymd: string, months: number): string | null {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(ymd)) return null;
  const [y, m, d] = ymd.split("-").map(Number);
  const dt = new Date(Date.UTC(y, m - 1 + months, d));
  const yy = dt.getUTCFullYear();
  const mm = String(dt.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(dt.getUTCDate()).padStart(2, "0");
  return `${yy}-${mm}-${dd}`;
}
